### ISSUE TITLE
Wee_extension Stuck on v2.0.0

### ISSUE THREAD

**Issue by techfixpros** [gjr80/weewx-weewx-wd#7]
WeeWx 4.5.1 .deb
WeeWx-WD 2.1.3

Upgraded from stale bitbucket build after removing via wee_extension --uninstall Weewx-WD. Installed via wee_extension --install <filename> to 2.0.0. Completed the instructions, started and confirmed no crashes or errors, and all files are being generated. Installed 2.1.3 via same process sans uninstall. Wee_extension --list still shows 2.0.0.

Verified /usr/share/weewx/user/wd.py matches v2.1.3 build.

**Comment by gjr80** [comment]
Thanks for letting me know, should be fixed now. Somehow the v2.0.0 installer was included in the v2.1.3 extension package. The only effect will have been to incorrectly report the installed version number, the installer code has not changed since v2.0.0.
