### ISSUE TITLE
the file "clientraw.txt" is not generated

### ISSUE THREAD

**Issue by venirb** [gjr80/weewx-weewx-wd#8]
i did fresh install of weewx latest version 4.9.1. I installed weewx-weewx-wd-master.zip. Clientrav.txt file is not generated. clientrawdaily, clientrawextra.txt and clientrawhour.txt are generated and updated. Operating system Arch Linux v.22 Sikaris. I have other extensions installed and they work fine. 
[log1.txt](https://github.com/gjr80/weewx-weewx-wd/files/10371741/log1.txt)

**Comment by gjr80** [comment]
Hi, as per the [readme](https://github.com/gjr80/weewx-weewx-wd/blob/master/README.md) this WeeWX extension is no longer being developed or supported. Note also the latest version of this extension will only work with WeeWX v4.5.1 and earlier - it will not work with WeeWX v4.9.1.

Depending on your requirements you may find the [WeeWX-Saratoga extension](https://github.com/gjr80/weewx-saratoga) may meet your needs.
